/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for TicketController controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { TicketUpdate, RequestOptions, TicketCreate, PageQuery, PageResponseTicketSummary, TicketDetails } from "../models";

@Injectable({ providedIn: "root" })
export class TicketControllerService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    updateTicket(ticketUpdate: TicketUpdate, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    updateTicket(ticketUpdate: TicketUpdate, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    updateTicket(ticketUpdate: TicketUpdate, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    updateTicket(ticketUpdate: TicketUpdate, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/ticket/update`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, ticketUpdate, requestOptions);
    }

    createTicket(ticketCreate: TicketCreate, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    createTicket(ticketCreate: TicketCreate, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    createTicket(ticketCreate: TicketCreate, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    createTicket(ticketCreate: TicketCreate, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/ticket/create`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, ticketCreate, requestOptions);
    }

    getSummaryList1(pageQuery: PageQuery, observe?: 'body', options?: RequestOptions<'blob'>): Observable<PageResponseTicketSummary>;
    getSummaryList1(pageQuery: PageQuery, observe?: 'response', options?: RequestOptions<'blob'>): Observable<HttpResponse<PageResponseTicketSummary>>;
    getSummaryList1(pageQuery: PageQuery, observe?: 'events', options?: RequestOptions<'blob'>): Observable<HttpEvent<PageResponseTicketSummary>>;
    getSummaryList1(pageQuery: PageQuery, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/ticket/summary`;

        const requestOptions: any = {
            observe: observe as any,
            responseType: 'blob' as 'blob',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    getDetailsById1(id: number, observe?: 'body', options?: RequestOptions<'blob'>): Observable<TicketDetails>;
    getDetailsById1(id: number, observe?: 'response', options?: RequestOptions<'blob'>): Observable<HttpResponse<TicketDetails>>;
    getDetailsById1(id: number, observe?: 'events', options?: RequestOptions<'blob'>): Observable<HttpEvent<TicketDetails>>;
    getDetailsById1(id: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/ticket/details/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            responseType: 'blob' as 'blob',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    deleteTicketById(id: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    deleteTicketById(id: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    deleteTicketById(id: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    deleteTicketById(id: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/ticket/delete/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }
}
