/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for SprintController controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { SprintUpdate, RequestOptions, SprintCreate, PageQuery, PageResponseSprintSummary, SprintDetails } from "../models";

@Injectable({ providedIn: "root" })
export class SprintControllerService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    updateSprint(sprintUpdate: SprintUpdate, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    updateSprint(sprintUpdate: SprintUpdate, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    updateSprint(sprintUpdate: SprintUpdate, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    updateSprint(sprintUpdate: SprintUpdate, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/sprint/update`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, sprintUpdate, requestOptions);
    }

    createSprint(sprintCreate: SprintCreate, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    createSprint(sprintCreate: SprintCreate, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    createSprint(sprintCreate: SprintCreate, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    createSprint(sprintCreate: SprintCreate, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/sprint/create`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, sprintCreate, requestOptions);
    }

    getSummaryList2(pageQuery: PageQuery, observe?: 'body', options?: RequestOptions<'blob'>): Observable<PageResponseSprintSummary>;
    getSummaryList2(pageQuery: PageQuery, observe?: 'response', options?: RequestOptions<'blob'>): Observable<HttpResponse<PageResponseSprintSummary>>;
    getSummaryList2(pageQuery: PageQuery, observe?: 'events', options?: RequestOptions<'blob'>): Observable<HttpEvent<PageResponseSprintSummary>>;
    getSummaryList2(pageQuery: PageQuery, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/sprint/summary`;

        const requestOptions: any = {
            observe: observe as any,
            responseType: 'blob' as 'blob',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    getDetailsById2(id: number, observe?: 'body', options?: RequestOptions<'blob'>): Observable<SprintDetails>;
    getDetailsById2(id: number, observe?: 'response', options?: RequestOptions<'blob'>): Observable<HttpResponse<SprintDetails>>;
    getDetailsById2(id: number, observe?: 'events', options?: RequestOptions<'blob'>): Observable<HttpEvent<SprintDetails>>;
    getDetailsById2(id: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/sprint/details/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            responseType: 'blob' as 'blob',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    deleteSprintById(id: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    deleteSprintById(id: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    deleteSprintById(id: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    deleteSprintById(id: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/sprint/delete/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }
}
