/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for TicketCommentController controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { TicketCommentUpdate, RequestOptions, TicketCommentCreate, PageQuery, PageResponseTicketCommentDetails } from "../models";

@Injectable({ providedIn: "root" })
export class TicketCommentControllerService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    updateTicketComment(ticketCommentUpdate: TicketCommentUpdate, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    updateTicketComment(ticketCommentUpdate: TicketCommentUpdate, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    updateTicketComment(ticketCommentUpdate: TicketCommentUpdate, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    updateTicketComment(ticketCommentUpdate: TicketCommentUpdate, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/ticketComment/update`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, ticketCommentUpdate, requestOptions);
    }

    createTicketComment(ticketCommentCreate: TicketCommentCreate, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    createTicketComment(ticketCommentCreate: TicketCommentCreate, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    createTicketComment(ticketCommentCreate: TicketCommentCreate, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    createTicketComment(ticketCommentCreate: TicketCommentCreate, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/ticketComment/create`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, ticketCommentCreate, requestOptions);
    }

    getDetailsList(ticketId: number, pageQuery: PageQuery, observe?: 'body', options?: RequestOptions<'blob'>): Observable<PageResponseTicketCommentDetails>;
    getDetailsList(ticketId: number, pageQuery: PageQuery, observe?: 'response', options?: RequestOptions<'blob'>): Observable<HttpResponse<PageResponseTicketCommentDetails>>;
    getDetailsList(ticketId: number, pageQuery: PageQuery, observe?: 'events', options?: RequestOptions<'blob'>): Observable<HttpEvent<PageResponseTicketCommentDetails>>;
    getDetailsList(ticketId: number, pageQuery: PageQuery, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/ticketComment/all/${ticketId}`;

        const requestOptions: any = {
            observe: observe as any,
            responseType: 'blob' as 'blob',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    deleteTicketCommentById(id: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    deleteTicketCommentById(id: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    deleteTicketCommentById(id: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    deleteTicketCommentById(id: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/ticketComment/delete/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }
}
