/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for UserController controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { PageQuery, RequestOptions, PageResponseUserSummary, UserDetails } from "../models";

@Injectable({ providedIn: "root" })
export class UserControllerService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    getSummaryList(pageQuery: PageQuery, observe?: 'body', options?: RequestOptions<'blob'>): Observable<PageResponseUserSummary>;
    getSummaryList(pageQuery: PageQuery, observe?: 'response', options?: RequestOptions<'blob'>): Observable<HttpResponse<PageResponseUserSummary>>;
    getSummaryList(pageQuery: PageQuery, observe?: 'events', options?: RequestOptions<'blob'>): Observable<HttpEvent<PageResponseUserSummary>>;
    getSummaryList(pageQuery: PageQuery, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/user/summary`;

        const requestOptions: any = {
            observe: observe as any,
            responseType: 'blob' as 'blob',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    getSprintParticipants(sprintId: number, pageQuery: PageQuery, observe?: 'body', options?: RequestOptions<'blob'>): Observable<PageResponseUserSummary>;
    getSprintParticipants(sprintId: number, pageQuery: PageQuery, observe?: 'response', options?: RequestOptions<'blob'>): Observable<HttpResponse<PageResponseUserSummary>>;
    getSprintParticipants(sprintId: number, pageQuery: PageQuery, observe?: 'events', options?: RequestOptions<'blob'>): Observable<HttpEvent<PageResponseUserSummary>>;
    getSprintParticipants(sprintId: number, pageQuery: PageQuery, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/user/participants/sprint/${sprintId}`;

        const requestOptions: any = {
            observe: observe as any,
            responseType: 'blob' as 'blob',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    getProjectParticipants(projectId: number, pageQuery: PageQuery, observe?: 'body', options?: RequestOptions<'blob'>): Observable<PageResponseUserSummary>;
    getProjectParticipants(projectId: number, pageQuery: PageQuery, observe?: 'response', options?: RequestOptions<'blob'>): Observable<HttpResponse<PageResponseUserSummary>>;
    getProjectParticipants(projectId: number, pageQuery: PageQuery, observe?: 'events', options?: RequestOptions<'blob'>): Observable<HttpEvent<PageResponseUserSummary>>;
    getProjectParticipants(projectId: number, pageQuery: PageQuery, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/user/participants/project/${projectId}`;

        const requestOptions: any = {
            observe: observe as any,
            responseType: 'blob' as 'blob',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    getDetailsById(id: string, observe?: 'body', options?: RequestOptions<'blob'>): Observable<UserDetails>;
    getDetailsById(id: string, observe?: 'response', options?: RequestOptions<'blob'>): Observable<HttpResponse<UserDetails>>;
    getDetailsById(id: string, observe?: 'events', options?: RequestOptions<'blob'>): Observable<HttpEvent<UserDetails>>;
    getDetailsById(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/user/details/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            responseType: 'blob' as 'blob',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }
}
