/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for ProjectController controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { ProjectUpdate, RequestOptions, ProjectCreate, PageQuery, PageResponseProjectSummary, ProjectDetails } from "../models";

@Injectable({ providedIn: "root" })
export class ProjectControllerService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    updateProject(projectUpdate: ProjectUpdate, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    updateProject(projectUpdate: ProjectUpdate, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    updateProject(projectUpdate: ProjectUpdate, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    updateProject(projectUpdate: ProjectUpdate, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/project/update`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, projectUpdate, requestOptions);
    }

    createProject(projectCreate: ProjectCreate, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    createProject(projectCreate: ProjectCreate, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    createProject(projectCreate: ProjectCreate, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    createProject(projectCreate: ProjectCreate, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/project/create`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, projectCreate, requestOptions);
    }

    getSummaryList3(pageQuery: PageQuery, observe?: 'body', options?: RequestOptions<'blob'>): Observable<PageResponseProjectSummary>;
    getSummaryList3(pageQuery: PageQuery, observe?: 'response', options?: RequestOptions<'blob'>): Observable<HttpResponse<PageResponseProjectSummary>>;
    getSummaryList3(pageQuery: PageQuery, observe?: 'events', options?: RequestOptions<'blob'>): Observable<HttpEvent<PageResponseProjectSummary>>;
    getSummaryList3(pageQuery: PageQuery, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/project/summary`;

        const requestOptions: any = {
            observe: observe as any,
            responseType: 'blob' as 'blob',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    getDetailsById3(id: number, observe?: 'body', options?: RequestOptions<'blob'>): Observable<ProjectDetails>;
    getDetailsById3(id: number, observe?: 'response', options?: RequestOptions<'blob'>): Observable<HttpResponse<ProjectDetails>>;
    getDetailsById3(id: number, observe?: 'events', options?: RequestOptions<'blob'>): Observable<HttpEvent<ProjectDetails>>;
    getDetailsById3(id: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/project/details/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            responseType: 'blob' as 'blob',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    deleteProjectById(id: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    deleteProjectById(id: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    deleteProjectById(id: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    deleteProjectById(id: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/project/delete/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }
}
