/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { HttpContext, HttpHeaders } from "@angular/common/http";
export interface TicketCommentUpdate {
    id: number;
    comment: string;
}

export interface TicketUpdate {
    id: number;
    title: string;
    description: string;
    assignedUserId: string;
    priority: 'LOW' | 'MEDIUM' | 'HIGH';
    status: 'BACKLOG' | 'IN_PROGRESS' | 'IN_TESTING' | 'COMPLETED';
}

export interface SprintUpdate {
    id: number;
    title: string;
    description: string;
    startDate: Date;
    dueDate: Date;
    status: 'PLANNED' | 'ACTIVE' | 'DONE' | 'PAUSED';
}

export interface ProjectUpdate {
    id: number;
    title: string;
    description: string;
    profilePicture?: string;
    status: 'PLANNED' | 'ACTIVE' | 'DONE' | 'ARCHIVED';
}

export interface TicketCommentCreate {
    comment: string;
    ticketId: number;
    parentCommentId?: number;
}

export interface TicketCreate {
    title: string;
    description: string;
    assignedUserId: string;
    priority: 'LOW' | 'MEDIUM' | 'HIGH';
    status: 'BACKLOG' | 'IN_PROGRESS' | 'IN_TESTING' | 'COMPLETED';
    sprintId: number;
}

export interface SprintCreate {
    title: string;
    description: string;
    startDate: Date;
    dueDate: Date;
    status: 'PLANNED' | 'ACTIVE' | 'DONE' | 'PAUSED';
    projectId: number;
}

export interface ProjectCreate {
    title: string;
    description: string;
    profilePicture?: string;
    status: 'PLANNED' | 'ACTIVE' | 'DONE' | 'ARCHIVED';
}

export interface PageQuery {
    page: number;
    size: number;
    search?: string;
    filterBy?: string;
}

export interface PageResponseUserSummary {
    currentPage: number;
    size: number;
    totalElements: number;
    totalPages: number;
    content: Array<UserSummary>;
}

export interface UserSummary {
    id: string;
    name: string;
    profilePicture?: string;
}

export interface UserDetails {
    id: string;
    name: string;
    job: string;
    profilePicture?: string;
}

export interface PageResponseTicketCommentDetails {
    currentPage: number;
    size: number;
    totalElements: number;
    totalPages: number;
    content: Array<TicketCommentDetails>;
}

export interface TicketCommentDetails {
    id: number;
    userSummary: UserSummary;
    comment: string;
    parentCommentId?: number;
    createdAt: Date;
    updatedAt?: Date;
}

export interface PageResponseTicketSummary {
    currentPage: number;
    size: number;
    totalElements: number;
    totalPages: number;
    content: Array<TicketSummary>;
}

export interface TicketSummary {
    id: number;
    title: string;
    priority: 'LOW' | 'MEDIUM' | 'HIGH';
    status: 'BACKLOG' | 'IN_PROGRESS' | 'IN_TESTING' | 'COMPLETED';
}

export interface TicketDetails {
    id: number;
    title: string;
    description: string;
    userSummary: UserSummary;
    priority: 'LOW' | 'MEDIUM' | 'HIGH';
    status: 'BACKLOG' | 'IN_PROGRESS' | 'IN_TESTING' | 'COMPLETED';
    closedAt?: Date;
}

export interface PageResponseSprintSummary {
    currentPage: number;
    size: number;
    totalElements: number;
    totalPages: number;
    content: Array<SprintSummary>;
}

export interface SprintSummary {
    id: number;
    title: string;
    startDate: Date;
    dueDate: Date;
    status: 'PLANNED' | 'ACTIVE' | 'DONE' | 'PAUSED';
}

export interface SprintDetails {
    id: number;
    title: string;
    description: string;
    startDate: Date;
    dueDate: Date;
    endDate?: Date;
    status: 'PLANNED' | 'ACTIVE' | 'DONE' | 'PAUSED';
}

export interface PageResponseProjectSummary {
    currentPage: number;
    size: number;
    totalElements: number;
    totalPages: number;
    content: Array<ProjectSummary>;
}

export interface ProjectSummary {
    id: number;
    title: string;
    profilePicture?: string;
    status: 'PLANNED' | 'ACTIVE' | 'DONE' | 'ARCHIVED';
}

export interface ProjectDetails {
    id: number;
    title: string;
    description: string;
    profilePicture?: string;
    status: 'PLANNED' | 'ACTIVE' | 'DONE' | 'ARCHIVED';
}

export interface NotificationDetails {
    type: 'TICKET_ASSIGNED' | 'TICKET_STATUS_CHANGED';
    ticketSummary: TicketSummary;
    isRead: boolean;
    readAt: Date;
}

export interface PageResponseNotificationDetails {
    currentPage: number;
    size: number;
    totalElements: number;
    totalPages: number;
    content: Array<NotificationDetails>;
}

/** Request Options for Angular HttpClient requests */
export interface RequestOptions<TResponseType extends 'arraybuffer' | 'blob' | 'json' | 'text'> {
    headers?: HttpHeaders;
    reportProgress?: boolean;
    responseType?: TResponseType;
    withCredentials?: boolean;
    context?: HttpContext;
}
